README.md

* Correct links of issue forms in `README.md`
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
Click links of bug report and feature request on README.md
```
* You are guided to the forms using the new GitHub input template
n/a

fix: issue form links

---

.github/workflows/test.yml
README.md
sonar-project.properties

Now that the project is public, we can perform the onboarding in sonarcloud. Fixes #179
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
```
* ...

feat: sonarcloud onboarding

---

README.md

* Adding CII Badge to repository
* Closes #180  
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
n/a
CII Badge is visible on README.md
n/a

chore: add CII badge

---

README.md

Adds a status badge for codeql to the README
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
```
* ...

chore: add codeql badge to README.md

---

docs/data-sources/subaccounts.md
internal/provider/datasource_subaccounts.go
internal/provider/datasource_subaccounts_test.go
internal/provider/fixtures/datasource_subaccounts.all.yaml

PR for basic test of datasource for subaccounts; closes #106 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
go test ./...
```
* All test pass successfully
n/a

feat: test of datasource subaccounts

---

DEVELOPER.md
docs/index.md
examples/provider/provider.tf

* Update of developer documentation
* CLoses #187 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
Execute the steps described in the `DEVELOPER.md` file
```
You should be able to successfully setup a local version of the Terraform provider
n/a

fix: developer documentation

---

README.md
docs/index.md
templates/index.md.tmpl

Added best practice reference of Hashicorp documentation to repo and official documentation. Closes #206 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
n/a
n/a
n/a

Chore: Best practices

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/codeql.yml

Enhancement of workflows and templates:
* Exclude changes in `*.tf` files from CodeQL checks
* Add a mandatory field for bug reports to specify the provider version
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
n/a
n/a
n/a

chore: additions to workflows

---

.github/workflows/semantic-pr.yml

This PR introduces a linter to enforce semantic PRs
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
Execute a PR
PR must meet the semantic PR conventions
See <https://www.conventionalcommits.org/en/v1.0.0/>

feat(workflow): lint for semantic PRs

---

DEVELOPER.md

Now that we have conventional commits #210 enforced, we should imho describe it in the developer documentation. For that reason I've added a section `Howto Commit` which describes exactly this.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

chore(developer-docs): howto commit

---

docs/resources/globalaccount_role_collection_assignment.md
internal/provider/fixtures/resource_globalaccount_role_collection_assignment.yaml
internal/provider/fixtures/resource_globalaccount_role_collection_assignment_with_origin.yaml
internal/provider/resource_globalaccount_role_collection_assignment.go
internal/provider/resource_globalaccount_role_collection_assignment_test.go

- adding test and fixtures for globalaccount role collection assignment resource
- adding missing id field required for testing (resource and doc)
* Adding test for the globalaccount role collection assignment resource
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
go test ./...
```
* tests are green

test: for resource_globalaccount_role_collection_assignment

---

internal/btpcli/facade_services_instance_test.go

Just a little refactoring to receive a 100% rating with goreport.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
```
* ...

refactor(facade_service_instance): simplify code

---

docs/resources/directory.md
internal/btpcli/facade_accounts_directory.go
internal/btpcli/facade_accounts_directory_test.go
internal/provider/fixtures/resource_directory.parent_directory.yaml
internal/provider/resource_directory.go
internal/tfutils/tfutils.go

* This PR introduces label support for directories
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* Test the code via unit tests:
```
go test ./...
```
* Alternative: Build Terraform provider and create a directory with or without labels 
* Directory gets created as configured
An additional test for labels cannot be created, dependency to PR #219

feat: label support for directories

---

internal/btpcli/facade_accounts_subaccount.go
internal/btpcli/facade_accounts_subaccount_test.go
internal/provider/resource_subaccount.go
internal/tfutils/tfutils.go

* This PR enables the provisioning of optional input fields for the creation of a subaccount (most important part: labels)
* To keep the setup compatible some adjustments needed to be made in the `tfutils.go`
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
Step 1: Execute go test ./...
Step 2: Create a subaccount via a terraform script
```
* Test are executed successfully
* Subaccount can be created including labels
n/a

feat: subaccount labels

---

docs/resources/directory_role_collection_assignment.md
internal/provider/fixtures/resource_directory_role_collection_assignment.yaml
internal/provider/fixtures/resource_directory_role_collection_assignment_with_origin.yaml
internal/provider/resource_directory_role_collection_assignment.go
internal/provider/resource_directory_role_collection_assignment_test.go

- adding test and fixtures for directory role collection assignment resource
- adding missing id field required for testing
- generate docs
* Closes #122 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
go test ./...
```
* test run successful

test: for resource_directory_role_collection_assignment

---

.github/release.yml

* Adding formatting for automatically generated release notes
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
Create release notes
```
* Check that automatically created release notes based on labels are created
See <https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes>

feat(workflow): automated release notes

---

docs/index.md
examples/provider/provider.tf

The provider reference is case sensitive and thus we should use `SAP/btp` instead of `sap/btp`.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: provider reference
```
```
```
* ...

fix(provider): reference must be case sensitive

---

internal/provider/helper_doc_values_format.go
internal/provider/helper_doc_values_format_test.go

* ...
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```
```
* ...

fix: escaped the pipe symbol in the description in the format helper

---

internal/provider/provider_test.go

* The go-vcr package used for recording and replaying http requests during tests provides an option to 'SkipRequestLatency' which is enabled by this change. While the overall duration of the tests is only reduced by approx. 20%, single tests are sped up by over 75%.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
go test ./...
```
* test execution should take shorter than without this change

feat: test speedup by enabling 'SkipRequestLatency'

---

.vscode/launch.json

* Adding a global launch configuration for VSCode
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Improvement of development setup
```
```
Start the debugger in VSCode via the launch configuration
```
* the Debugger started and is running

chore(vscode): add launch configuration for provider debugging

---

.github/dependabot.yml

* Add Terraform ecosystem to dependabot
``
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: enhancement of workflow setup
```
n/a
n/a
n/a

chore(workflow): add terraform ecosystem to dependabot

---

docs/index.md
examples/provider/provider.tf

* fixed typo in provider.tf example - misleading example value of global account subdomain
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: typo in example 
```
```
```
* ...

fix(documentation): typo and description of provider.tf

---

docs/resources/subaccount.md
internal/provider/fixtures/resource_subaccount.usage_set.yaml
internal/provider/resource_subaccount.go
internal/provider/resource_subaccount_test.go
internal/provider/type_subaccount.go

* Enable user to set a sub account for productive usage
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
execute test fixture for subaccount resource
```
* All tests successfull

fix: Add usage to subaccount resource

---

internal/provider/fixtures/resource_directory.parent_directory.yaml
internal/provider/resource_directory.go

* Temporary workaround to mitigate inconsistent response from server
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: temporary workaround
```
```
Execute the recorded test
```
* Test passes
Workaround must be removed once fix is available

fix(temp): temporary fix for inconsistent status response for directory deletion

---

internal/provider/provider.go

* Error in provider.go due to duplicate assignment of role resource for subaccount
```
[ ] Yes
[X ] No
```
```
[X] Bugfix
[ ] Feature
```
```
go test ./...
```
* Tests suceed 
n/a

fix: duplicate role resource in provider.go

---

docs/resources/subaccount_role_collection.md
examples/resources/btp_subaccount_role_collection/import.sh
internal/provider/fixtures/resource_subaccount_role_collection.yaml
internal/provider/fixtures/resource_subaccount_role_collection_import_error.yaml
internal/provider/resource_subaccount_role_collection.go
internal/provider/resource_subaccount_role_collection_test.go

* Add import functionality of `subaccount_role_collection`
* Closes #90  
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
Execute the documented import of the resource
```
* The state of the remote resource is imported into a `tfstate` file
n/a

feat(resource): Import subaccount rolecollection

---

docs/resources/directory_role_collection.md
examples/resources/btp_directory_role_collection/import.sh
internal/provider/fixtures/resource_directory_role_collection.error_import.yaml
internal/provider/fixtures/resource_directory_role_collection.multiple_roles.yaml
internal/provider/fixtures/resource_directory_role_collection.no_description.yaml
internal/provider/fixtures/resource_directory_role_collection.with_description.yaml
internal/provider/resource_directory_role_collection.go
internal/provider/resource_directory_role_collection_test.go

* Add import functionality of `directory_role_collection`
* Closes  #97 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
Execute the documented import of the resource
```
* The state of the remote resource is imported into a `tfstate` file
Automated test skipped due to combined key

feat(resource): Import resource directory_role_collection

---

internal/btpcli/facade_accounts_subaccount.go
internal/btpcli/facade_accounts_subaccount_test.go
internal/provider/fixtures/resource_subaccount.yaml
internal/provider/provider_test.go
internal/provider/resource_subaccount.go
internal/provider/resource_subaccount_environment_instance_test.go

Sets a custom request matcher which considers the following request properties:
- Request URL
- HTTP method
- Request body
- Subdomain header
- Custom IdP header
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
go test ./...
```
* tests should still be green
Resolves #253

feat: Improve matching of replayed interactions during test execution

---

.github/workflows/cleanup-action-caches.yml

* Cleanup caches of GH Actions after merge of PRs
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Improvement of workflow setup
```
n/a
n/a
n/a

chore(workflows): add workflow to cleanup GH action caches after merge

---

internal/provider/fixtures/resource_subaccount_environment_instance.yaml
internal/provider/resource_subaccount_environment_instance.go
internal/provider/resource_subaccount_environment_instance_test.go

* Fix of import of environment instances. The wrong attribute was used for the `subaccount_id`
* As a follow-up fix the READ of the resources needed to be adjusted in case of an import to be consistent with the state based on the parameters
Closes #316 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
go test ./...
```
* Tests are executed susccesfully
n/a

fix: import of environment instance fails

---

internal/provider/fixtures/resource_subaccount_service_binding.yaml
internal/provider/fixtures/resource_subaccount_service_binding_import_error.yaml
internal/provider/resource_subaccount_service_binding.go
internal/provider/resource_subaccount_service_binding_test.go

This PR adds the missing polling logic for the `delete` function of the resource for service binding
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
go test ./...
```
Text fixture needed change of service instance for service binding due to issues on Canary with IBAN service (beta)

fix: polling for service binding (delete)

---

internal/version/version.go

So far we report "dev" as the provider version to the cli server. This should be replaced during the build process with the actual version of the provider.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...

fix: provider version in useragent

---

docs/index.md
examples/provider/provider.tf

Preparing the release. The provider documentation should refer to the new version.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...

fix(docs): provider version

---

internal/btpcli/facade_accounts_resource_provider.go
internal/btpcli/facade_accounts_resource_provider_test.go
internal/provider/fixtures/resource_globalaccount_resource_provider.update.yaml
internal/provider/resource_globalaccount_resource_provider.go
internal/provider/resource_globalaccount_resource_provider_test.go

Adds support for the update operation to the globalaccount resource provider resource.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
go test ./...
```
```
...
```
* ...
Resolves #103

feat(resource): support update of "btp_globalaccount_resource_provider"

---

.goreleaser.yml

* This PR adds the configuration to the `goreleaser.yaml` to use GitHub native APIs for release note generation
* Closes #332  
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Setup of release process
```
n/a
n/a
n/a

chore: adjust goreleaser.yaml for release note creation

---

.github/scripts/fixtureDriftDetect.sh
.github/workflows/test.yml

Adds a script for detecting file changes with regards to lines matching a given regex. This is used to detect changes in test fixtures based on lines with the keys id, url and status. Changes lead to a warning and a diff output that should be checked before submitting the PR.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
go test ./...
```
```
...
```
* ...

feat: Add fixture drift detection to github action for tests

---

internal/tfutils/tfutils.go

Resolves #315
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

fix(sonar): Reduce complexity of internal/tfutils/tfutils.go

---

internal/btpcli/facade_accounts_entitlement.go

Resolves #313
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

fix: Reduce complexity of facade_accounts_entitlement.go

---

docs/resources/subaccount_environment_instance.md
examples/resources/btp_subaccount_environment_instance/resource.tf

* This PR correct the example delivered in the documentation for the resource `environment_instance`. The user defined in the JSON parameter is not a valid parameter and was removed
* fixes #385 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Check the generated documentation for the environment instance
the example does not contain the user block
see flow described in [help.sap,com](https://help.sap.com/docs/btp/sap-business-technology-platform/setting-up-global-account-via-command-line) on setting up the environment and how to add org users (step 11 to 14).
The following organizational tasks must be completed …

docs: correction of environment instance sample

---

docs/index.md
examples/provider/provider.tf

Prepare docs for 0.3.0 release
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...

chore: prepare docs for 0.3.0 release

---

docs/resources/directory.md
docs/resources/subaccount_environment_instance.md
docs/resources/subaccount_service_instance.md
examples/resources/btp_directory/resource.tf
examples/resources/btp_subaccount_environment_instance/resource.tf
examples/resources/btp_subaccount_service_instance/resource.tf

Some of the sample files are not correctly formatted. I just ran `terraform fmt -recursive .` in the repository root and regenerated the docs.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: code formatting
```
```bash
go test ./...
```
```
...
```
* ...

fix: code formatting

---

docs/index.md
examples/provider/provider.tf
internal/provider/provider.go

* Preparation of next Terraform provider release - update of 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: prep work for next release
```
```bash
go test ./...
```
n/a

chore: preparation of  version 0.4.0

---

internal/provider/fixtures/resource_globalaccount_trust_configuration.full_spec.yaml
internal/provider/fixtures/resource_globalaccount_trust_configuration.invalid_origin.yaml
internal/provider/fixtures/resource_globalaccount_trust_configuration.yaml
internal/provider/resource_globalaccount_trust_configuration_test.go

resolves #360
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: missing tests
```
```bash
go test ./...
```
```
...
```
* ...

test: re-activating tests for resource_globalaccount_trust_configuration

---

docs/index.md
templates/index.md.tmpl

* The authentication via `username` and `password` relies on the BTP CLI functionality. There are some documented issues around the SAP Universal ID. This issue and the note describing how to resolve this is now referenced in the documentation
* Fixes #415 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
n/a
* Check that markdown file is updates
n/a

docs: add information about SAP Universal ID logon

---

internal/btpcli/facade_accounts_entitlement.go
internal/btpcli/facade_accounts_entitlement_test.go
internal/provider/resource_directory_entitlement.go

* fixes #417 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

fix: sonar cloud finding - number of function parameters

---

internal/btpcli/facade_services_instance.go
internal/btpcli/facade_services_instance_test.go
internal/provider/fixtures/resource_subaccount_service_instance.import_error.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_labels.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_labels_change.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_parameters.yaml
internal/provider/fixtures/resource_subaccount_service_instance_with_timeouts.yaml
internal/provider/resource_subaccount_service_instance.go
internal/provider/resource_subaccount_service_instance_test.go
internal/provider/type_subaccount_service_instance.go

* This PR fixes the label handling for the resource `subaccount_service_instance`
*  The handling is consistent with the service binding and the update functionality is fixed
* Closes #448 
```
[X] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
This change changes the `state` format for this resource

fix: label handling for service instances on subaccounts

---

.github/workflows/test.yml

* This PR updates the test matrix for the Terraform build and test configuration
* It add the version 1.6 as the latest available for our customers
* It removes version 1.1 as it has reached its end of life over a year ago
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: dependency
```
```bash
go test ./...
```
The version 1.6 is the first version released under BSL/BUSL. However, as customers can use this version without any impact, we need to make sure that the provider runs on this version. 
The …

chore(dependency): updated test matrix for supported Terraform versions

---

.github/workflows/sbom-creation.yml

* This PR adds a GH Action for SBOM creation
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Compliance
```
* Execute the GH Action via manually triggering it
* The result of the GH Action should be a stored artifact that contains the SBOM in SPDX format
Needs to be decided if this should be added to the release as a dedicated artifact

chore: GH Action for SBOM creation

---

docs/index.md
internal/btpcli/client.go
internal/btpcli/client_test.go
internal/btpcli/clienttypes.go
internal/provider/provider.go

Adds support for passcode authentication with SAP IAS. Fixes #458 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```bash
go test ./...
```
```
...
```
* ...

feat(btpcli): add support for passcode auth

---

internal/btpcli/client.go

* Change usage of FIXME to TODO and remove misleading Sonar Cloud Code Smell reporting
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Sonar Cloud
```
n/a
* No FIXME code smell in Sonar Cloud Reporting
n/a

fix: change FIXME to TODO

---

internal/provider/fixtures/resource_directory.error_change_features.yaml
internal/provider/resource_directory.go
internal/provider/resource_directory_test.go

* This PR fixes the error handling as follow-up task of #445 
* The following changes are made:
* environment instances - landscape label: `requiresReplace` is enabled -> **No Action required**
* subaccount - parent id: `requiresReplace` is enabled -> **No Action required**
* directory - parent_id: Add `requiresReplace` which makes handling consistent to subaccount
* directory - features: Add error handling for change of features (temporary limitation see #471 )
* closes #466 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
Verify that the following …

fix: error handling of non-updateable fields of directory

---

internal/provider/provider.go

* closes #486 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Sonar cloud finding
```
```bash
go test ./...
```
n/a

fix: sonar cloud finding

---

docs/resources/globalaccount_trust_configuration.md
docs/resources/subaccount_trust_configuration.md
examples/resources/btp_globalaccount_trust_configuration/import.sh
examples/resources/btp_subaccount_trust_configuration/import.sh
internal/provider/fixtures/resource_globalaccount_trust_configuration.complete.yaml
internal/provider/fixtures/resource_globalaccount_trust_configuration.invalid_idp.yaml
internal/provider/fixtures/resource_globalaccount_trust_configuration.minimal.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.complete.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.import_error.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.minimal.yaml
internal/provider/resource_globalaccount_trust_configuration.go
internal/provider/resource_globalaccount_trust_configuration_test.go
internal/provider/resource_subaccount_trust_configuration.go
internal/provider/resource_subaccount_trust_configuration_test.go

* This PR fixes the wrong ID assignment for the subaccount trust configuration
* Test scenarios are enhanced with import
* Documentation is updated 
* Sync of setup in global account trust configuration to avoid usage of ID
* Closes #491 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

fix: failing import of subaccount trust configuration

---

internal/btpcli/facade_services_instance.go
internal/provider/fixtures/resource_subaccount_service_instance.import_error.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_labels.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_labels_change.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_parameters.yaml
internal/provider/fixtures/resource_subaccount_service_instance.wo_parameters.yaml
internal/provider/fixtures/resource_subaccount_service_instance_with_timeouts.yaml
internal/provider/resource_subaccount_service_instance.go

* Based on the delivery of solutions for two internal tickets, several workarounds can be removed from the code for service instance creation
* Closes #33 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: remove workarounds
```
```bash
go test ./...
```
- Tests needed to be re-recorded due to change of input parameters after removal of workaround
- Update scenario cannot be fully aligned due to response of CLI server

fix: remove workarounds from service instance creation

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

* Update documentation for provider setup to 0.6.0
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Check generated documentation
documentation contains updated version
n/a

docs: switch to release 0.6.0 for provider documentation

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

* Update release verson
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update release version
```
```bash
go test ./...
```
* Check that `provider.md` contains latest version number

chore: prep release 0.6.0-beta2

---

docs/index.md
internal/provider/provider.go
templates/index.md.tmpl

* add link to tutorial (fix [issue 533](https://github.com/SAP/terraform-provider-btp/issues/533)).
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

docs: update get started

---

.github/ISSUE_TEMPLATE/bug_report.yml

* Update of issue template for bugs
* New: clarified section about Terraform CLI version and Terraform provider version
* Optional new area for role collections assigned to user executing Terraform configuration
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: GitHub issue template update
```
Open a Issue of type "bug"
Template is used with new sections mentioned above
n/a

chore: update issue template for bug reports

---

integration/README.md
integration/main.tf
integration/provider.tf
integration/variables.tf

This change provides scripts for setting up a global account for integration testing and fixture recording.
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Other: Infrastructure as Code for Integration Testing
```
* Test the code via automated tests -> tests should work with newly created global account.

ci: Terraform Integration Landscape Setup

---

internal/btpcli/facade_accounts_subaccount.go
internal/btpcli/facade_accounts_subaccount_test.go
internal/provider/datasource_subaccount_entitlements.go
internal/provider/fixtures/resource_subaccount.change_to_used_for_production.yaml
internal/provider/fixtures/resource_subaccount.full_config.yaml
internal/provider/fixtures/resource_subaccount.used_for_production.yaml
internal/provider/fixtures/resource_subaccount.yaml
internal/provider/resource_subaccount.go
internal/provider/resource_subaccount_entitlement.go
internal/provider/type_subaccount.go
internal/provider/type_subaccount_entitlement.go

* This PR enhances the deletion logic of subaccounts under managed directories to consider the right level for authorization checks
* Closes #544 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

fix: deletion of subaccounts under managed directories

---

docs/data-sources/directory_user.md
docs/data-sources/directory_users.md
docs/data-sources/globalaccount_user.md
docs/data-sources/globalaccount_users.md
docs/data-sources/subaccount_user.md
docs/data-sources/subaccount_users.md
docs/resources/directory_role_collection_assignment.md
docs/resources/globalaccount_role_collection_assignment.md
docs/resources/subaccount_role_collection_assignment.md
internal/provider/datasource_directory_user.go
internal/provider/datasource_directory_users.go
internal/provider/datasource_globalaccount_user.go
internal/provider/datasource_globalaccount_users.go
internal/provider/datasource_subaccount_user.go
internal/provider/datasource_subaccount_users.go
internal/provider/resource_directory_role_collection_assignment.go
internal/provider/resource_globalaccount_role_collection_assignment.go
internal/provider/resource_subaccount_role_collection_assignment.go

* Refine of documetation of `origin` parameter
* Remove defaulting to LDAP
* Stress that optional parameter is necessary only for Custom IdP sceanrios
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Check markdown files
defautling to ldap is no longer mentioned, hint for custom IdP is there

docs: refine origin description

---

internal/provider/datasource_directory_role_collection_test.go
internal/provider/fixtures/datasource_directory_role_collection.not_security_enabled.yaml
internal/provider/fixtures/datasource_directory_role_collection.yaml
internal/provider/fixtures/datasource_directory_role_collections.not_security_enabled.yaml
internal/provider/fixtures/datasource_directory_role_collections.yaml

* Makes test recording landscape independent
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Directory Role Collection Test

---

internal/provider/datasource_directory_roles_test.go
internal/provider/fixtures/datasource_directory_roles.not_security_enabled.yaml
internal/provider/fixtures/datasource_directory_roles.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Directory Roles Tests

---

internal/provider/datasource_directory_users_test.go
internal/provider/fixtures/datasource_directory_users.custom_idp.yaml
internal/provider/fixtures/datasource_directory_users.default_idp.yaml
internal/provider/fixtures/datasource_directory_users.non_existing_idp.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Directory Users Tests

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

* Update for RC release
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update of version tags
```
```bash
go test ./...
```
n/a
* [X ] The PR has the matching labels assigned to it.
* [X ] If the PR closes an issue, the issue is referenced.

chore: update release version

---

internal/provider/datasource_directory_role_test.go
internal/provider/fixtures/datasource_directory_role.not_security_enabled.yaml
internal/provider/fixtures/datasource_directory_role.yaml
internal/provider/fixtures/datasource_directory_role_collection.not_security_enabled.yaml
internal/provider/fixtures/datasource_directory_role_collection.yaml
internal/provider/fixtures/datasource_directory_role_collections.not_security_enabled.yaml
internal/provider/fixtures/datasource_directory_role_collections.yaml
internal/provider/fixtures/datasource_directory_roles.not_security_enabled.yaml
internal/provider/fixtures/datasource_directory_roles.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Directory Role Tests

---

internal/provider/datasource_subaccount_app_test.go
internal/provider/fixtures/datasource_subaccount_app.by_id.yaml
internal/provider/fixtures/datasource_subaccount_apps.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Subaccount App Tests

---

internal/provider/datasource_subaccount_environments_test.go
internal/provider/fixtures/datasource_subaccount_environments.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Subaccount Environments Tests

---

internal/provider/datasource_subaccount_labels_test.go
internal/provider/fixtures/datasource_subaccount_labels.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Subaccount Labels Tests

---

internal/provider/datasource_subaccount_security_settings_test.go
internal/provider/fixtures/datasource_subaccount_security_settings.by_id.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Subaccount Security Settings Tests

---

.github/workflows/schema-regression-test.yml
regrsssion-test/README.md
regrsssion-test/main.tf
regrsssion-test/provider.tf
regrsssion-test/variables.tf

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...

chore: test-setup

---

internal/provider/datasource_subaccount_service_bindings_test.go
internal/provider/fixtures/datasource_subaccount_service_bindings.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Subaccount Service Bindings Tests

---

.github/workflows/schema-regression-test.yml
assets/provider-config-ghaction.txt
regression-test/README.md
regression-test/main.tf
regression-test/provider.tf
regression-test/variables.tf

* Basic setup for regression testing of Terraform provider schema
* The flow is:
* Setup an environment with a stable provider release
* Keep the state information
* Switch to a local provider build based on repo
* Execute `terraform plan`
* If deviations are found in plan an issue is created
* The infrastructure is deleted after the execution
* Closes #529 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Execute GH Action workflow for regression testing
* workflow gets executed successfully
* The technical user setup is currently …

chore: base setup of regression testing

---

internal/provider/datasource_subaccount_trust_configurations_test.go
internal/provider/fixtures/datasource_subaccount_trust_configurations.subaccount_exists.yaml
internal/provider/fixtures/datasource_subaccount_trust_configurations.subaccount_not_existing.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Subaccount Trust Configurations Tests

---

internal/provider/datasource_subaccount_trust_configuration_test.go
internal/provider/fixtures/datasource_subaccount_trust_configuration.custom_idp_exists.yaml
internal/provider/fixtures/datasource_subaccount_trust_configuration.custom_idp_not_existing.yaml
internal/provider/fixtures/datasource_subaccount_trust_configuration.default.yaml
internal/provider/fixtures/datasource_subaccount_trust_configurations.subaccount_exists.yaml
internal/provider/fixtures/datasource_subaccount_trust_configurations.subaccount_not_existing.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Subaccount Trust Configuration Tests

---

internal/provider/fixtures/resource_directory_role_collection_assignment.import_error.yaml
internal/provider/fixtures/resource_directory_role_collection_assignment.with_origin.yaml
internal/provider/fixtures/resource_directory_role_collection_assignment.with_origin_and_attribute.yaml
internal/provider/fixtures/resource_directory_role_collection_assignment.with_origin_and_group.yaml
internal/provider/fixtures/resource_directory_role_collection_assignment.yaml
internal/provider/resource_directory_role_collection_assignment_test.go

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Directory Role Collection Assignment Tests

---

internal/provider/fixtures/resource_subaccount_security_settings.complete.yaml
internal/provider/resource_subaccount_security_settings_test.go

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Subaccount Security Settings Tests

---

internal/provider/fixtures/resource_subaccount_role_collection_assignment.import_error.yaml
internal/provider/fixtures/resource_subaccount_role_collection_assignment.with_origin.yaml
internal/provider/fixtures/resource_subaccount_role_collection_assignment.with_origin_and_attribute.yaml
internal/provider/fixtures/resource_subaccount_role_collection_assignment.with_origin_and_group.yaml
internal/provider/fixtures/resource_subaccount_role_collection_assignment.yaml
internal/provider/resource_subaccount_role_collection_assignment_test.go

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Subaccount Role Collection Assignment Tests

---

internal/provider/datasource_subaccount_service_binding_test.go
internal/provider/fixtures/datasource_subaccount_service_binding.by_id.yaml
internal/provider/fixtures/datasource_subaccount_service_binding.by_name.yaml
internal/provider/fixtures/datasource_subaccount_service_bindings.yaml
internal/provider/provider_test.go

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Subaccount Service Binding Tests

---

internal/provider/datasource_subaccount_service_instance_test.go
internal/provider/fixtures/datasource_subaccount_service_instance.by_id.yaml
internal/provider/fixtures/datasource_subaccount_service_instance.by_name.yaml
internal/provider/fixtures/datasource_subaccount_service_instances.all.yaml
internal/provider/fixtures/datasource_subaccount_service_instances.labelsfilter.yaml
internal/provider/fixtures/datasource_subaccount_service_instances.namefilter.yaml
internal/provider/fixtures/datasource_subaccount_service_instances.namefilter_variant.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Subaccount Service Instance Tests

---

internal/provider/datasource_subaccount_subscription_test.go
internal/provider/fixtures/datasource_subaccount_subscription.by_id_and_plan.yaml
internal/provider/fixtures/datasource_subaccount_subscriptions.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Subaccount Subscription Tests

---

internal/provider/datasource_subaccount_test.go
internal/provider/fixtures/datasource_subaccount.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Datasource Subaccount Tests

---

internal/provider/fixtures/resource_directory_role_collection.error_import.yaml
internal/provider/fixtures/resource_directory_role_collection.multiple_roles.yaml
internal/provider/fixtures/resource_directory_role_collection.no_description.yaml
internal/provider/fixtures/resource_directory_role_collection.update.yaml
internal/provider/fixtures/resource_directory_role_collection.with_description.yaml
internal/provider/resource_directory_role_collection_test.go

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Directory Role Collection Tests

---

internal/provider/fixtures/resource_subaccount_role_collection.import_error.yaml
internal/provider/fixtures/resource_subaccount_role_collection.update.yaml
internal/provider/fixtures/resource_subaccount_role_collection.update_rm_desc.yaml
internal/provider/fixtures/resource_subaccount_role_collection.update_wo_desc.yaml
internal/provider/fixtures/resource_subaccount_role_collection.yaml
internal/provider/resource_subaccount_role_collection_test.go

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Subaccount Role Collection Tests

---

.github/workflows/release.yml
.github/workflows/schema-regression-test.yml
.github/workflows/test.yml
regression-test/provider.tf
regression-test/variables.tf

* Enhancement of release workflow with automatic test execution (regular as well as regression)
* Change of test workflow to make it reusable/callable from other workflows
* Refine regression test templates to consider IdP
* Refine workflow definition to consider IdP
* Closes #597 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Test/Release setup
```
Execute release workflow
* Test are run before the workflow
Depends on #592 

chore: enhance release workflow with tests

---

internal/provider/fixtures/resource_subaccount_trust_configuration.complete.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.error_missing_identityprovider.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.import_error.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.minimal.yaml
internal/provider/resource_subaccount_trust_configuration_test.go

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Subaccount Trust Configuration Tests

---

internal/provider/fixtures/resource_subaccount_environment_instance.update.yaml
internal/provider/fixtures/resource_subaccount_environment_instance.with_timeout.yaml
internal/provider/fixtures/resource_subaccount_environment_instance.yaml
internal/provider/resource_subaccount_environment_instance_test.go

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Resource Subaccount Environment Instance Tests

---

.github/workflows/test.yml

* Update test matrix of Terraform versions, removed version 1.2 (last update: September 2022)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
See <https://endoflife.date/terraform>

chore: remove outdated TF version

---

.github/workflows/release.yml
.github/workflows/schema-regression-test.yml
regression-test/main.tf

* This ÜR conatins some fixes for the GH Action for regression tests as well as a **deactivation** as necessary step in the release process
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: GH workflow setup and release prcess
```
n/a
n/a
Follow-up issue is created: #650 

fix: regression test workflow

---

.github/workflows/feature-request-response.yml

* Updated GH action workflow to fix the issue which prevented the execution of the workflow.
* Fixes #651 
```
[ ] Yes
[X] No
```
```
[ X] Bugfix
[ ] Feature
```

chore: update feature-request-response.yml

---

.github/workflows/compatibility-test.yml
assets/compat_template.md

* Sample GitHub workflow to do basic compatibility checks against the OpenTofu CLI
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: test setup
```
Execute the GitHub workflow
Workflow gets executed and creates/destroys basic setup validating several resources
This validation does not imply that this provider officially supports the OpenTofu CLI or will provide bug fixes to be compliant with the CLI.

chore: opentofu compatibility check

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/test.yml

* Include the latest version of the Terraform CLI into the test setup
* Adjust issue template 
* Closes #662 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Internal setup
```
```bash
go test ./...
```
```
Execute the GitHub workflow test.yml 
```
* GitHub workflow gets executed successfully and the test matrix contains the latest version of the Terraform CLI
n/a

chore: include version 1.7

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf
regression-test/provider.tf

* Adjustments of documentation for release of RC2
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Check that all sources reference RC2 
n/a

chore: prep work for rc2

---

.github/workflows/release.yml

* Enhances the call of the test workflow to inherit the secrets of the calling workflow
* Closes #671 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
Execute the workflow 
* Sonar Cloud step of workflow gets executed i.e. the SONAR_TOKEN gets injected
see <https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow>

chore: fix test in release workflow

---

.github/workflows/codeql.yml

* Workaround for https://github.com/github/codeql-action/issues/1842 and https://github.com/github/codeql/issues/13992
* Manual setup of Golang; Go version from `go.mod` file
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: GitHub workflow Setup
```

chore: codeql setup

---

docs/resources/subaccount_service_instance.md
templates/resources/subaccount_service_instance.md.tmpl

Edit restriction for the service instance resource
* tried to make the restriction more explicit
* refinement of documentation introduced by #630 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
n/a
Generated documentation
n/a

docs: update subaccount_service_instance.md.tmpl

---

docs/resources/subaccount_environment_instance.md
examples/resources/btp_subaccount_environment_instance/resource.tf

* Improve example documentation for environment instance i.e., Cloud Foundry concenring the landscape label parameter
* Closes #692 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Markdown is regenerated and contains the updated example
See https://github.com/SAP/terraform-provider-btp/issues/686#issuecomment-1917682843

docs: improvement of env instance for CF

---

regression-test/README.md
regression-test/main.tf
regression-test/variables.tf

* Update of regression test setup due to missing application
* Alignment and cleanup concerning integration test setup
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: refinement/update of regression test setup
```
* Execute GH Action ` Regression Test - Terraform Provider`
Verify that the run is executed successfully
n(a

chore: regression setup update

---

regression-test/main.tf

* Fix regression test, missing entitlement
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Setup regression test
```

chore: fix regression setup

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

* Prep release 1.0.0
* Update of docs and templates
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
n/a
* Templates point to version 1.0.0
n/a

chore: prep release 1.0.0

---

internal/provider/provider.go
internal/provider/resource_directory.go

This PR fixed minor code smells suggested by sonar scans.
resolves: #715 
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...

fix: code quality checks

---

.github/workflows/schema-regression-test.yml

- Update the regression-schema-test to follow the go.mod file
- Fixes #718
* Prevent the regression-schema-test from failing due to outdated go version
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
- regression-schema test passes

fix: go version - regression-schema-test

---

internal/provider/datasource_globalaccount_with_hierarchy.go

* Fixes with the Sonar Cloud finding [Rename this local variable to match the regular expression "^(_|[a-zA-Z0-9]+)$".](https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=CONSISTENT&resolved=false&id=SAP_terraform-provider-btp&open=AY3ulfjL0gCBEfP1KJl_)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Naming convention/Sonar Cloud fincing
```
```bash
go test ./...
```
n/a

fix: sonar cloud issue naming convention

---

.github/workflows/integration-test.yml

- Template to start and test the integration workflow
- TODO-Configure resto fo the workflow
* Setup the initial integration workflow to follow through and test the actual test.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: github action
```
This is an initial PR for issue 461

chore: Initial integration workflow

---

internal/provider/fixtures/resource_globalaccount_trust_configuration.complete.yaml
internal/provider/fixtures/resource_globalaccount_trust_configuration.invalid_idp.yaml
internal/provider/fixtures/resource_globalaccount_trust_configuration.minimal.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.complete.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.error_missing_identityprovider.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.import_error.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.minimal.yaml
internal/provider/resource_globalaccount_trust_configuration_test.go
internal/provider/resource_subaccount_trust_configuration_test.go

Previously, the custom IDP used for specific tests had fixed values, restricting their compatibility with users' preferred IDPs. To address this issue, an environment variable named "BTP_TEST_IDP" has been implemented. Users can now configure this variable in the ***devcontainer.env file*** according to their preferences. It is important to note that re-recording fixtures is necessary to avoid any mismatches. Alternatively, users can run the tests with the default custom IDP configuration already in place.
fix #728 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go …
```

fix: Generalised the custom IDP for the tests

---

internal/provider/datasource_subaccount.go

* Refactoring of code due to Sonar Cloud finding (<https://sonarcloud.io/project/issues?impactSeverities=HIGH&resolved=false&sinceLeakPeriod=true&id=SAP_terraform-provider-btp>)
* Fixes #743 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

fix: sonar cloud finding - function complexity

---

docs/resources/subaccount_environment_instance.md
examples/resources/btp_subaccount_environment_instance/resource.tf

* Corrects the example data for SAP Kyma environment instance creation as reported in #742 
* Fixes #742
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
n/a
* Check the generated markdown file for the resource to reflect the right parameters
See <https://help.sap.com/docs/btp/sap-business-technology-platform/provisioning-and-update-parameters-in-kyma-environment?locale=en-US>

docs: fix parameters for Kyma environment instance

---

.github/workflows/schema-regression-test.yml

* This PR refines the drift detection flow to rely on the `-detailed-exitcode` parameter of Terraform in combination with the step context parameters `outcome`
* The refinement makes the flow leaner and is consistent with the best practices for drift detection
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Execute the GH Action
n/a
n/a

chore: refine drift detection

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf
regression-test/provider.tf

- Update reference to 1.2.0
- Update reference to 1.1.0 in regression test
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
n/a

chore: prep release 1.2.0

---

README.md

* Update year of copyright
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Check README.md

docs: update copyright

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/test.yml

* Clean up of the test matrix for the Terraform CLI versions, namely removal of outdated versions
* Addition of Terraform  version 1.8.x to the test matrix 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: setup of tests
```
* Execution of `test.yml` GitHub Action
* Test matrix contains the TF versions 1.5, 1.6, 1.7 and 1.8
**ATTENTION** - This PR must be merged at a point when no PRs are open.
After merge, the settings for the PR checks in the GitHub repository must be updated, namely the list of the required status checks ""Terraform Provider Acceptance Tests " in the branch …

chore: version cleanup of TF, inclusion of version 1.8.x

---

internal/provider/fixtures/resource_subaccount_service_instance.import_error.yaml
internal/provider/fixtures/resource_subaccount_service_instance.sharing_error.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_labels.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_labels_change.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_parameters.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_sharing_conf_changed.yaml
internal/provider/fixtures/resource_subaccount_service_instance.with_sharing_enabled.yaml
internal/provider/fixtures/resource_subaccount_service_instance.wo_parameters.yaml
internal/provider/fixtures/resource_subaccount_service_instance_with_timeouts.yaml
internal/provider/resource_subaccount_service_instance.go

* This PR fixes an issue with the state handling of failed service instance resource creations or updates
* Before this PR a state was persisted with new values despite the operation to reach the new state failed
* This could cause wrong plan results as the `parameters` of service instances cannot be read form the platform
* closes #779 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
Execute a invalid state change with wrong parameters of a service instance -> terraform apply fails
Execute a terraform plan
```
Verify that …

fix: state handling for service instance creation or update fails 

---

docs/data-sources/directory.md
docs/data-sources/directory_labels.md
docs/data-sources/directory_roles.md
docs/data-sources/directory_users.md
docs/data-sources/globalaccount.md
docs/data-sources/globalaccount_roles.md
docs/data-sources/globalaccount_security_settings.md
docs/data-sources/globalaccount_trust_configuration.md
docs/data-sources/globalaccount_trust_configurations.md
docs/data-sources/globalaccount_users.md
docs/data-sources/globalaccount_with_hierarchy.md
docs/data-sources/subaccount_labels.md
docs/data-sources/subaccount_roles.md
docs/data-sources/subaccount_security_settings.md
docs/data-sources/subaccount_trust_configuration.md
docs/data-sources/subaccount_trust_configurations.md
docs/data-sources/subaccount_users.md
docs/resources/directory.md
docs/resources/directory_entitlement.md
docs/resources/directory_role_collection.md
docs/resources/globalaccount_resource_provider.md
docs/resources/globalaccount_role_collection.md
docs/resources/globalaccount_security_settings.md
docs/resources/globalaccount_trust_configuration.md
docs/resources/subaccount.md
docs/resources/subaccount_entitlement.md
docs/resources/subaccount_environment_instance.md
docs/resources/subaccount_role_collection.md
docs/resources/subaccount_security_settings.md
docs/resources/subaccount_trust_configuration.md

* Fixes docu generation drift due to terraform-docs fix delivered with 0.19.1
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make generate
```
* Documentation is up to date
See https://github.com/hashicorp/terraform-plugin-docs/releases/tag/v0.19.1

docs: fix issue with drifted documentation due to terraform-docs fix in version 0.19.1

---

docs/data-sources/subaccount_subscriptions.md
internal/provider/datasource_subaccount_subscriptions.go

* add description of `subaccount_id` for data source `subscriptions`
* closes #784 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Check documentation
* Subaccount ID field has description
n/a

docs: issue 784

---

.github/workflows/release.yml

fix: Temporarly Disable Check

---

.github/workflows/release.yml

- Revert temporal fix for bug 795
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[x] Other... Please describe: Revert temporal work
```
na
na

fix: Revert Release Workflow

---

docs/resources/globalaccount_trust_configuration.md
docs/resources/subaccount_trust_configuration.md
examples/resources/btp_globalaccount_trust_configuration/import.sh
examples/resources/btp_subaccount_trust_configuration/import.sh

* Fix of typo in docs
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* check for correct spaces in documentation 
n/a

docs: typo in import comment

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

- Update reference to 1.3.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: 
```
n/a
n/a

chore: prep release 1.3.0

---

.github/workflows/release.yml

* Update of goreleaser GH Action to latest version -> containing node20 dependency
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update of dependencies/GH Action
```
* Execute GH Action
* Action gets executed
https://github.com/goreleaser/goreleaser-action/releases/tag/v5.0.0

chore: update goreleaser action

---

README.md
guides/QUICKSTART.md

This PR adds a new quick start guide which can be linked to the readme.
* ...
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
NA
NA
* ...
PR https://github.com/SAP/terraform-provider-btp/issues/811

docs: adding quick start guide

---

.lycheeignore
guides/QUICKSTART.md

* Fix broken links
* reformat markdown
* closes #815 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Run GH Action with periodic link checker
* GH Action executes without findings
developers.sap.com throws 403s when checked via GH Action since weekend. Put it on ignore list

docs: fix broken links

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

* Update reference to 1.4.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release preps
```
```bash
go test ./...
```
n/a
n/a

chore: prep release v1.4.0

---

docs/data-sources/subaccount.md
docs/resources/directory.md
docs/resources/directory_entitlement.md
examples/data-sources/btp_subaccount/data-source.tf
examples/resources/btp_directory/resource.tf
examples/resources/btp_directory_entitlement/resource.tf
integration/main.tf
integration/variables.tf
regression-test/variables.tf

I've noticed some issues with the formatting of the terraform files. This is the outcome of:
```
terraform fmt -recursive .
go generate ./...
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...

chore: terraform fmt

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

Update reference to 1.5.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release prep
```

chore: Prep Release v1.5.0

---

regression-test/variables.tf

Temporary fix for the regression tests.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
go test ./...
```

fix: removed variable idp from regression tests

---

.devcontainer/default/devcontainer.json
.devcontainer/withenvfile/devcontainer.json
README.md
go.mod
internal/btpcli/client.go
internal/btpcli/client_test.go

The PR build was failing due to failure of lint tests in 2 files. The reason of failure is usage of non-constant format string in a call to fmt.Errorf and fmt.Fprintf, the fixes will ensure to prevent any unintended interpretation of format specifiers.
Closes: #887
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[X] Other... Please describe: Version Upgrade
```
```bash
go test ./...
```
```
...
```
* ...

fix: Broken Lint Tests & chore: upgrade of go version 

---

.devcontainer/default/devcontainer.json
.devcontainer/withenvfile/devcontainer.json

* Remove the automatic install of xdg-utils due to failures in the devcontainer setup
* Add comment on SSo setup in devcontainer file
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: rework dev container setup
```
* Start the devcontainer
* The devcontainer starts without errors
n/a

chore: rework devcontainer setup

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

* Update reference to 1.6.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release prep
```
```bash
go test ./...
```
NA

chore: Prep Release v1.6.0

---

CONTRIBUTING.md

* Update Contribution Guidelines
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: OSPO guidelines
```
n/a
n/a
n/a

docs: upate contribution guidelines

---

.lycheeignore

* Add link to gnu.org to skipped links as there seems to be a rate limting issue
* Closes #908
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: repo setup
```
* Execute GH Action for Link Checking
* Link check pass
n/a

fix: link checker

---

internal/provider/resource_subaccount_entitlement.go

Closes #902 
Implemented the retry logic in the Read function of the resource subaccount entitlement to overcome the rate limiting issue faced. This is accomplished by placing the GET call within a loop, enabling the function to manage rate limiting errors accordingly.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
go test ./...
```

fix: added retry logic for reading resource subaccount entitlement

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

* Update reference to 1.7.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release Prep
```

chore: Prep works v1.7.0

---

docs/resources/directory_entitlement.md
examples/resources/btp_directory_entitlement/import.sh

* Fix wrong comment on resourc eimport example
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
* Documentation for import of `directory_entitlement` is correct
n/a

docs: fix wrong resource in comment

---

README.md

Added message in Readme for mentioning OpenTofu support
* ...
```
[ ] Yes
[x] No
```
[ ] Bugfix
[ ] Feature
NA
Very the OpenTofu Compatibility section in Readme.md
NA
NA

docs: Add message for OpenTofu support

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

* Update reference to 1.7.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release Update
```
```bash
go test ./...
```
n/a

chore: Prep works v1.8.0

---

internal/provider/resource_subaccount_service_binding.go

*  fix #936 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

fix: unexpected update of a btp_subaccount_service_binding

---

.github/workflows/test.yml

* Remove version 1.10 from test matrix due to errors in flow in post create phase
* The fix is just a temporary measure. Needs to be fixed in follow up issue
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
Follow Up issue created for analysis of error #973

fix: remove terraform 1.10 from test matrix

---

internal/btpcli/clienttypes_test.go
internal/btpcli/facade_accounts_entitlement_test.go
internal/btpcli/facade_accounts_global_account_test.go
internal/provider/datasource_subaccount_environment_instance_test.go
internal/provider/datasource_subaccount_environment_instances_test.go
internal/provider/datasource_subaccount_service_plan_test.go
internal/provider/fixtures/datasource_subaccount_environment_instance.yaml
internal/provider/fixtures/datasource_subaccount_environment_instances.yaml
internal/provider/fixtures/datasource_subaccount_service_plan.err_with_subaccount_only.yaml
internal/provider/fixtures/provider.error_cli_server_url.yaml
internal/provider/provider_test.go

Closes: https://github.com/SAP/terraform-provider-btp/issues/958
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Improving test coverage for Sonar
```
```bash
go test ./...
```
```
...
```
* ...
* [] Possible follow-up items are created and linked.

test: Improve Sonar Tests Coverage

---

docs/data-sources/subaccount_entitlements.md
internal/provider/datasource_subaccount_entitlements.go

* Fix the documentation for the subaccount entitlements data source
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Updated doc

chore: Fix Documentation

---

go.mod
go.sum

* Update Golang dependencies (`go get -u ./...` and `go get -t -u ./...`)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Dependency update
```
```bash
go test ./...
```
closes security finding CVE-2024-45338

chore: update Go dependencies

---

.reuse/dep5
README.md
guides/DRIFTDETECTION.md
guides/IMPORT.md

* Yearly update references of copyright/licenses
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
```bash
go test ./...
```
n/a

chore: update year references

---

README.md

* Fix wrong link in `README` for drift detection
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Link to drift detection is referencing the right document
n/a

docs: fix wrong link for drift detection

---

.github/workflows/test.yml

- Update deprected GH Action for Sonar Cloud scans
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Internal Setup
```
```bash
make test
```
see https://github.com/SonarSource/sonarcloud-github-action
```
This action is deprecated and will be removed in a future release. Please use the sonarqube-scan-action action instead. The sonarqube-scan-action is a drop-in replacement for this action.
```

chore: update Sonar Cloud GH Action

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

* ...
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Other- Preparation for v1.9.0 release
```

chore: Prep works v1.9.0

---

internal/provider/datasource_globalaccount_resource_provider_test.go
internal/provider/datasource_globalaccount_resource_providers_test.go
internal/provider/fixtures/datasource_globalaccount_resource_provider.yaml
internal/provider/fixtures/datasource_globalaccount_resource_providers.yaml
internal/provider/fixtures/resource_globalaccount_resource_provider.create.yaml
internal/provider/fixtures/resource_globalaccount_resource_provider.update.yaml
internal/provider/fixtures/resource_globalaccount_resource_provider.update_wo_description.yaml
internal/provider/resource_globalaccount_resource_provider_test.go

Uncommented the code and re-recorded test fixtures for Global Account Resource Provider Resource & Datasource
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: test setup
```
```bash
go test ./...
```
n/a

chore: Updated Test Fixtures

---

.github/workflows/test.yml

* Add version 1.10 of Terraform to test matrix
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: test setup
```
```bash
go test ./...
```
n/a

chore: add Terraform version 1.10 to test matrix

---

.github/workflows/schema-regression-test-opentofu.yml
.github/workflows/test-opentofu.yml

* Update OpenTofu version matrix to include latest release 1.9.*
* Update wrong configuration of tofu regression test (`tofu_version`)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
Release notes for OpenTofu 1.9.0: https://github.com/opentofu/opentofu/releases/tag/v1.9.0

chore: update tofu version for test matrix

---

.github/workflows/assign-project.yml

- GH Action to automaticllay assign issues and pull requests to the central project board
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: automation setup
```
```bash
make test
```
n/a

chore: assign issue/pr to central project

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

- Update references of provider version to 1.10.0
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Release prep
```
```bash
make test
```
See #1022

chore: prep release 1.10.0

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/test.yml

- Add new version of Terraform to test matrix
- Update issue template- Closes #1035 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
- See [release blog post](https://www.hashicorp.com/de/blog/terraform-1-11-ephemeral-values-managed-resources-write-only-arguments)
- Add test to PR checks after merge

chore: add new Terraform version to test matrix

---

.devcontainer/default/Dockerfile
.devcontainer/default/devcontainer.json
.devcontainer/withenvfile/devcontainer.json
.github/workflows/release.yml
.goreleaser.yml
README.md
go.mod

- Update Golang to latest version (1.24)
- Fix deprecation warnings of Goreleaser
- Closes #1025
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Upgrade Golang
```
```bash
make test
```
n/a

chore: Golang update

---

internal/btpcli/client.go

- The login flow is enhanced via a retry logic (3 retries with backoff)
- The logic is triggered if the CLI server reports a HTTP status code 500 or 504
- Closes #1038
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
n/a

feat: add retry logic for login calls

---

docs/index.md
internal/provider/provider.go
internal/provider/provider_test.go
templates/index.md.tmpl

- Added validators X509 login flow
- Updated and refined documentation for authentication flows
- Closes #1032
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
- Documentation contains examples for differnet authentication flows
n/a

docs: refine information and validation of authentication flows

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

- Prepare release 1.11.0
- Update example and bug template
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Preparation of release 1.11.0
```
```bash
make test
```
n/a

chore: prepare release 1.11.0

---

internal/btpcli/facade_accounts_subscription.go
internal/btpcli/facade_accounts_subscription_test.go
internal/provider/fixtures/resource_subaccount_subscription.import_error.yaml
internal/provider/fixtures/resource_subaccount_subscription.yaml
internal/provider/fixtures/resource_subaccount_subscription_update.yaml
internal/provider/fixtures/resource_subaccount_subscription_update_plan.update_error.yaml
internal/provider/fixtures/resource_subaccount_subscription_with_timeouts.yaml
internal/provider/resource_subaccount_subscription.go
internal/provider/resource_subaccount_subscription_test.go

- Added support to update plan and parameters for a subscription where plan and parameters are updatable.
- closes #1057 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```bash
make test
```

feat: support for subaccount subscription updates

---

docs/resources/subaccount.md
guides/MOVESUBACCOUNT.md
templates/resources/subaccount.md.tmpl

- Add documentation on limitation of moving subaccounts
- Closes #1069
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
- Check generated documentation of resource `btp_subaccount`
- Generated documentation contaisn link to the markdown of the limitation description
n/a

docs: add limitation for moving subaccounts

---

docs/data-sources/subaccount_security_settings.md
docs/resources/subaccount_security_settings.md
internal/provider/datasource_subaccount_security_settings.go
internal/provider/datasource_subaccount_security_settings_test.go
internal/provider/fixtures/datasource_subaccount_security_settings.by_id.yaml
internal/provider/fixtures/resource_subaccount_security_settings.complete.yaml
internal/provider/fixtures/resource_subaccount_security_settings.destroy.yaml
internal/provider/fixtures/resource_subaccount_security_settings_with_iframe_domains_list.complete.yaml
internal/provider/resource_subaccount_security_settings.go
internal/provider/resource_subaccount_security_settings_test.go
internal/provider/type_subaccount_security_settings.go

- Added new parameter `iframe_list`, which will take a list of strings to handle multiple iframe domains.
- closes #1066 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```

feat: handling of iframe domains in btp_subaccount_security_settings

---

internal/btpcli/facade_accounts_subaccount.go
internal/provider/fixtures/resource_subaccount.change_to_used_for_production.yaml
internal/provider/fixtures/resource_subaccount.full_config.yaml
internal/provider/fixtures/resource_subaccount.used_for_production.yaml
internal/provider/fixtures/resource_subaccount.yaml

- fix: issue with force deletion of subaccounts with new opt-in option
- recording of test fixtures
- closes #1078
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```
See release notes for SAP BTP April 17, 2025 - Opt-in for force deletion of subaccounts

fix: subaccount error during deletion

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

- Prepare for release 1.12.0
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Release preparation
```
```bash
make test
```

chore: prepare release 1.12.0

---

.github/workflows/test.yml

- Closes: https://github.com/SAP/terraform-provider-btp/issues/1093
- Added version 1.12
- Removed version 1.9
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Test Setup
```
```bash
make test
```

chore: Updated Terraform Version for Test Matrix

---

internal/provider/resource_subaccount_entitlement.go

- Improve error message for reading of entitlement when the prociessing status is failed
- This also helps to pin down issues when importing the resource
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```

fix: error message for entitlement status

---

internal/provider/resource_subaccount_entitlement.go

If the import of an entitlement on subaccount level fails die to the state `PROCESSING_FAILED`, we add the reson for the failure to the error message.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
This is a follow-up to #1099

feat: add entitlement error reason to output

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

- prepare for release 1.13.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release preparation
```
```bash
make test
```

chore: prepare release 1.13.0

---

.github/workflows/canary-regression-test.yml

Updated the workflow to be compatible with  canary landscape, Updating the region, cli_server_url, and IDP.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```

chore: update Terraform scripts for canary landscape compatibility

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

- Update release
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```bash
make test
```

chore: Prep v1.15.0

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf
integration/provider.tf

- Prpe release 1.15.1 (hotfix)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Release prepearation
```
```bash
make test
```
n/a

chore: prep hotfix release 1.15.1

---

docs/resources/directory.md
docs/resources/directory_entitlement.md
docs/resources/directory_role.md
docs/resources/directory_role_collection.md
docs/resources/globalaccount_role.md
docs/resources/subaccount_entitlement.md
docs/resources/subaccount_role.md
docs/resources/subaccount_role_collection.md
docs/resources/subaccount_subscription.md
examples/resources/btp_directory/import.sh
examples/resources/btp_directory_entitlement/import.sh
examples/resources/btp_directory_role/import.sh
examples/resources/btp_directory_role_collection/import.sh
examples/resources/btp_globalaccount_role/import.sh
examples/resources/btp_subaccount_entitlement/import.sh
examples/resources/btp_subaccount_role/import.sh
examples/resources/btp_subaccount_role_collection/import.sh
examples/resources/btp_subaccount_subscription/import.sh

- Fix typo in import sample of `btp_directory` resource that pointed to the wrong resource.
- Align formatting of import via import identity for all samples
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
n/a

docs: import samples typo and formatting

---

docs/index.md
templates/index.md.tmpl

- Update documentation to clarify login restrictions with SAP Univeral ID and mutliple S-/P-Users
- Add section about login with JWT Token
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
n/a

docs: update authentication information

---

.devcontainer/default/devcontainer.json
.devcontainer/withenvfile/devcontainer.json
.github/workflows/test.yml
btp/provider/datasource_subaccount.go
btp/provider/datasource_subaccounts.go
btp/provider/fixtures/resource_subaccount.change_to_used_for_production.yaml
btp/provider/fixtures/resource_subaccount.full_config.yaml
btp/provider/fixtures/resource_subaccount.skip_entitlements.yaml
btp/provider/fixtures/resource_subaccount.used_for_production.yaml
btp/provider/fixtures/resource_subaccount.with_managed_parent.yaml
btp/provider/fixtures/resource_subaccount.with_parent_hierarchy.yaml
btp/provider/fixtures/resource_subaccount.yaml
btp/provider/resource_subaccount.go
btp/provider/resource_subaccount_test.go
btp/provider/type_subaccount.go
docs/resources/subaccount.md
guides/IMPORT.md
internal/btpcli/facade_accounts_subaccount.go
internal/btpcli/facade_accounts_subaccount_test.go
templates/resources/subaccount.md.tmpl

- Add support of the `skip_entitlements` flag to the `subaccount` resource.
- As field cannot be updated, it is marked as `requires_replace` upon update.
- Adding data type for data sources as field cannot be read (resource data types cannot be reused)
- Update documentation to reflect the new field
- Updated documentation to reflect limitation of field in import
- closes #1174
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
n/a
The following organizational tasks must be …

feat: support attribute for skipping automatic entitlements
