SAP/terraform-provider-btp

.github/workflows/test.yml

Fixes 
```bash
INFO: Sensor Go Cover sensor for Go coverage [go]
ERROR: Coverage report can't be loaded, report file not found, ignoring this file cover.out.
```
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* check the scan log ([here](https://github.com/SAP/terraform-provider-btp/actions/runs/5333001472/jobs/9663028325?pr=203#step:5:96)). the error listed above shouldn't appear anymore
* check the coverage [here](https://sonarcloud.io/summary/overall?id=SAP_terraform-provider-btp) once merged
* ...

fix(sonarcloud): coverage reporting

---

internal/provider/datasource_directory_user_test.go
internal/provider/fixtures/datasource_directory_user.custom_idp.yaml
internal/provider/fixtures/datasource_directory_user.default_idp.yaml

While working on a different issue, I figured out that the tests for directory_user are wrongly setup. The IDP must be postfixed with `-platform` in order to retrieve valid values. 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* check the service response in the updated fixtures
* ...

fix(directory_user): custom idp in test must be postfixed with -platform

---

docs/data-sources/directory.md
docs/data-sources/globalaccount.md
docs/data-sources/subaccount.md
docs/data-sources/subaccounts.md
docs/resources/directory.md
docs/resources/subaccount.md
internal/provider/datasource_directory.go
internal/provider/datasource_globalaccount.go
internal/provider/datasource_subaccount.go
internal/provider/datasource_subaccounts.go
internal/provider/resource_directory.go
internal/provider/resource_subaccount.go

I'm trying to reduce the amount of abbreviations in the docs. E.g. `CF` -> `Cloud Foundry`, `NEO` -> `Neo`, `GUID` can be in most of the cases be simplified with just `ID`.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

docs: use less abbreviations

---

docs/index.md
internal/provider/provider.go

* Clarifies that 2FA is not suported
* Closes #261 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
n/a
* Check documetation
n/a

fix(documentation): clarify not supported 2FA flow in provider documentation

---

internal/btpcli/facade_accounts_subaccount.go
internal/btpcli/facade_accounts_subaccount_test.go

* Creating a subaccount linked to a directory leads to an error as the `parentId` parameter is used for connection to subaccount and not automatically set to the global-account value. This PR now sets the parameter explicitly in all creation scenarios
* Fixes #257  
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
Create subaccount under a directory
```
* Subaccount gets created under directory
n/a

fix(facade): transfer global account value when creating subaccount

---

internal/btpcli/client.go
internal/provider/provider.go
internal/provider/provider_test.go

* Add support for setting the identity provider from environment variable BTP_IDP during provider configuration. This is implemented analogously to BTP_USERNAME and BTP_PASSWORD including the required redaction of recorded fixtures. To prevent impact on existing fixtures, identity provider values are replaced by the empty string during redaction.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
1. go test ./...
2. Try local recording of text fixtures and use a custom idp user by setting all three of the env vars BTP_USERNAME, BTP_PASSWORD, BTP_IDP, setting the latter to the ias tenant …
```

feat: support custom idp login when recording test fixtures

---

internal/btpcli/facade_accounts_subaccount.go
internal/btpcli/facade_accounts_subaccount_test.go
internal/provider/resource_subaccount.go

* Adds additional fields to update operation (internal switch to obejct)
* Closes  #278 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
go test ./...
```
* Test execution succeeds
The use for production flag is excluded - tracked via #273

fix: update subaccount with missing fields

---

internal/provider/fixtures/resource_subaccount.yaml

* Fix recording of fixture for subaccount
* fixing error of update operation not found
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
go test ./...
```
* Tests succeed
n/a

fix: correct subaccount test recording

---

internal/provider/resource_directory.go

* Correction of Sonar Cloud Codesmell concerning error message in `resource_directory.go` ([Link](https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=SAP_terraform-provider-btp&open=AYk_ttKRlKSUjDzpECI)>)
* was indeed a bug (wrong error message in update case)
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
go test ./...
```
* Test are successful
n/a

fix: wrong error message in update of directory resource

---

internal/btpcli/facade_accounts_subscription.go
internal/btpcli/types/xsuaa_authz/model_user_reference.go
internal/tfutils/tfutils.go

* Aligning FIXME and TODO comments in code wrt priority of topic
* Changed three FIXME comments to TODO as non-major issues were addressed
* All major issues remain labeled as FIXME
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Sonar Cloud Findings
```
n/a
n/a
See Sonar Cloud Reporting -> Code Smells for Main branch

fix: reprioritized FIXME comments

---

internal/btpcli/facade_security_role_collection.go
internal/btpcli/facade_security_role_collection_test.go
internal/provider/fixtures/resource_directory_role_collection.error_import.yaml
internal/provider/fixtures/resource_directory_role_collection.no_description.yaml
internal/provider/fixtures/resource_directory_role_collection.update.yaml
internal/provider/fixtures/resource_directory_role_collection.with_description.yaml
internal/provider/fixtures/resource_globalaccount_role_collection.import_error.yaml
internal/provider/fixtures/resource_globalaccount_role_collection.update.yaml
internal/provider/fixtures/resource_globalaccount_role_collection.yaml
internal/provider/fixtures/resource_subaccount_role_collection.import_error.yaml
internal/provider/fixtures/resource_subaccount_role_collection.update.yaml
internal/provider/fixtures/resource_subaccount_role_collection.yaml
internal/provider/resource_directory_role_collection.go
internal/provider/resource_directory_role_collection_test.go
internal/provider/resource_globalaccount_role_collection.go
internal/provider/resource_globalaccount_role_collection_test.go
internal/provider/resource_subaccount_role_collection.go
internal/provider/resource_subaccount_role_collection_test.go
internal/tfutils/tfutils.go

Add support for update operation to role collection facade and resources
Also: Fix error message when adding roles to role-collection
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
go test ./...
```
Tests are green
Resolves #86
Resolves #99
Resolves #102

feat(resource): support role collection update

---

docs/resources/subaccount.md
internal/btpcli/facade_accounts_subaccount.go
internal/btpcli/facade_accounts_subaccount_test.go
internal/provider/fixtures/resource_subaccount_change_to_used_for_production.yaml
internal/provider/fixtures/resource_subaccount_used_for_production.yaml
internal/provider/resource_subaccount.go
internal/provider/resource_subaccount_test.go

* This PR adds the `usage` of a subaccount as optional parameter to the Terraform resource
* It contains some special logic needed to execute the mapping of the CLI parameters consistently to the possible values of the CIS responses/JSON responses from the CLI
* The test fixtures have been re-recorded and enhanced
* The documentation is updated  
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
go test ./...
```
* Test succed
Based on PR #288  
@Thanhphan1147 once again thanks for your contribution

feat: add usage parameter to subaccount resource

---

.github/PULL_REQUEST_TEMPLATE.md

* Refinement of PR template. Closes #323 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: refinement of PR template
```
n/a
n/a
n/a

chore: refinement of PR template

---

internal/provider/datasource_whoami.go
internal/provider/resource_directory_role_collection_assignment.go
internal/provider/resource_directory_role_collection_assignment_test.go
internal/provider/resource_globalaccount_role_collection_assignment.go
internal/provider/resource_globalaccount_role_collection_assignment_test.go
internal/provider/resource_subaccount_role_collection_assignment.go
internal/provider/resource_subaccount_role_collection_assignment_test.go

* Alignment of error messages according to Hashicorp best practices (see <https://developer.hashicorp.com/terraform/plugin/framework/diagnostics#creating-diagnostics>)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
n/a
n/a
n/a

docs: align error message punctuation to Terraform best practices

---

docs/data-sources/directory_entitlements.md
docs/data-sources/globalaccount_entitlements.md
docs/data-sources/subaccount_entitlements.md
internal/provider/datasource_directory_entitlements.go
internal/provider/datasource_globalaccount_entitlements.go
internal/provider/datasource_subaccount_entitlements.go

* Adds the field `category` to the data sources for entitlements 
* Closes #328 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
* Connected to changes mage in PR #318 
* No test re-recording needed as single fields are not evaluated

fix: missing field in datasources for entitlements

---

docs/data-sources/globalaccount.md
docs/data-sources/subaccount_service_binding.md
docs/data-sources/subaccount_service_offerings.md
docs/resources/directory.md
docs/resources/subaccount_service_binding.md
internal/provider/datasource_globalaccount.go
internal/provider/datasource_globalaccount_resource_provider.go
internal/provider/datasource_globalaccount_resource_providers.go
internal/provider/datasource_subaccount_service_binding.go
internal/provider/datasource_subaccount_service_offerings.go
internal/provider/resource_directory.go
internal/provider/resource_subaccount_service_binding.go

* Fix for misformatted tables in terraform registry
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
n/a
n/a
n/a

docs: fix for wrong format of tables in terraform registry

---

docs/resources/globalaccount_resource_provider.md
internal/btpcli/facade_accounts_resource_provider.go
internal/btpcli/facade_accounts_resource_provider_test.go
internal/btpcli/types/provisioning/resource_provider.go
internal/provider/datasource_globalaccount_resource_provider.go
internal/provider/datasource_globalaccount_resource_provider_test.go
internal/provider/datasource_globalaccount_resource_providers.go
internal/provider/datasource_globalaccount_resource_providers_test.go
internal/provider/fixtures/datasource_globalaccount_resource_provider.yaml
internal/provider/fixtures/datasource_globalaccount_resource_providers.yaml
internal/provider/fixtures/resource_globalaccount_resource_provider.create.yaml
internal/provider/resource_globalaccount_resource_provider.go
internal/provider/resource_globalaccount_resource_provider_test.go
internal/provider/type_globalaccount_resource_provider.go

The schema for the resource provider resource and datasources is fixed and corresponding tests are added. Furthermore, some attribute names were improved.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...
Resolves #337

fix(resource): fix schema and add tests for resource provider

---

.github/workflows/cleanup-action-caches.yml
.github/workflows/stale-handling.yml

* Adds handing of stale issues via GH Actions
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: improvement of setup
```
n/a
n/a
Also aligned the title of the GH action for cache cleanups.

chore: add stale handling for issues and prs

---

.github/ISSUE_TEMPLATE/bug_report.yml

* Improve issue template - more guidance on entering HCL configuration scripts
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Improvement of issue template
```
Open an issue of type bug
New guidance should be displayed as placeholder
n/a

chore: refine bug issue template

---

internal/provider/datasource_directory_roles.go
internal/provider/datasource_globalaccount_roles.go
internal/provider/datasource_subaccount_roles.go

Fixes #349 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...

fix(btp_subaccount_roles): mapping of role names

---

internal/provider/resource_subaccount_service_binding.go
internal/provider/resource_subaccount_service_instance.go
internal/provider/resource_subaccount_subscription.go

* Fix handling of errors during CRUD operations on app subscriptions, service instances and service bindings by explicitly handling failure state as no error is returned by API
* closes #351 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

fix: handling of errors for services, subscriptions and bindings

---

internal/provider/resource_subaccount_entitlement.go

* This PR fixes the handling of error scenarios when polling for a state change for the resource entitlement.
* Error that occurs looks basically like this if the entitlement fails:
```bash
When applying changes to btp_subaccount_entitlement.entitlement-quotas["xxx"], 
provider
│ "provider["registry.terraform.io/sap/btp"]" produced an unexpected new value: .amount: was cty.NumberIntVal(1), but now  
│ cty.NumberIntVal(0).
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
``` …

fix: error handling of entitlement polling

---

docs/index.md
internal/provider/provider.go

* Enhancement of documentation for 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

docs: enhance provider setup documentation

---

internal/provider/provider_test.go

Resolves #361
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```bash
go test ./...
```
```
...
```
* ...

feat: Add fixture record/replay log messages

---

docs/resources/subaccount_environment_instance.md
internal/provider/resource_subaccount_environment_instance.go

* The `parameters` parameter of the resource `subaccount_environment_instance` is changed to required as for Kyma and Cloud Foundry the corresponding JSON object must be provided to successfully create an enviroment instance.
* Fixes #378 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

fix: env instance parameters classification

---

internal/provider/resource_subaccount_environment_instance.go
internal/provider/resource_subaccount_service_instance.go

* This PR extends the timeouts for the creation of services instances and environment instances to 60 minutes
* This is a temporal workaround. The solution will be provided as described in #11 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: workaround for timeout issue with env instances
```
```bash
go test ./...
```
n/a

fix: extend timeout for service instance and env instance

---

internal/btpcli/facade_services_instance.go
internal/provider/fixtures/resource_subaccount_service_instance_import_error.yaml
internal/provider/fixtures/resource_subaccount_service_instance_with_parameters.yaml
internal/provider/fixtures/resource_subaccount_service_instance_wo_parameters.yaml

* This PR contains a workaround for the creation of service instances that return a non-JSON response when creation is triggered. This is currently the case for some services like HANA Cloud that return a 202 response
* The workaround is temporary and marked as TODO to be tracked via Sonar Cloud
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[X] Other... Please describe: temporary workaround
```
```bash
go test ./...
```
n/a

fix: workaround for service instance creation

---

internal/provider/resource_subaccount_entitlement.go

* Checking for `nil` entitlement retrieved during `READ` of resource. 
* Fixes #395 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
- Create a subaccount with an entitlement via terraform
- Manually remove the entitlement from the subaccount, leaving it in the terraform state
- Execute a "terraform plan"
```
* The result of the additional test step should be an error message during the plan
Manual deletion of resource needs to be handled by …

fix: nil pointer exception in subaccounts entitlement read

---

internal/btpcli/facade_accounts_subaccount.go

PR for  #342 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...
My colleague Thanh opened a pull request [here](https://github.com/SAP/terraform-provider-btp/pull/363) but he is not working with us anymore, so I'm taking his subject.

fix: Only add planName to subscribe request if it's not empty

---

docs/index.md
internal/btpcli/client.go
internal/btpcli/client_test.go
internal/btpcli/clienttypes.go
internal/provider/provider.go

Adding support for id token login to the provider configuration. The id token replaces username and password and is passed to a new special login endpoint of the btp CLI server.
The resulting session id is read from a response header. Currently, the response does not contain any authentication info, i.e. the terraform provider does not support the whoami datasource when logging in via id token.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
go test ./...
```
```
The automated tests only contain unit tests for the id token login since there is no …
```

feat: support login with id token

---

docs/data-sources/directory_roles.md
docs/data-sources/globalaccount_roles.md
docs/data-sources/subaccount_roles.md
internal/provider/datasource_directory_roles.go
internal/provider/datasource_directory_roles_test.go
internal/provider/datasource_globalaccount_roles.go
internal/provider/datasource_globalaccount_roles_test.go
internal/provider/datasource_subaccount_roles.go
internal/provider/datasource_subaccount_roles_test.go
internal/provider/fixtures/datasource_directory_roles.not_security_enabled.yaml
internal/provider/fixtures/datasource_directory_roles.yaml
internal/provider/fixtures/datasource_globalaccount_roles.yaml
internal/provider/fixtures/datasource_subaccount_roles.yaml

* In order to create customer-defined role collections the app name is needed for filtering the results of all available roles in a subaccount/directory/globalaccount. This PR introduces the field to the corresponding data sources.
* Closes #413 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
go test ./...
```
The API for getting a dedicated single role does not return this field. Consequently,  we added the field exclusively to the "list" data sources
The following organizational tasks …

feat: add app name to data sources for roles

---

internal/btpcli/facade_accounts_subaccount.go
internal/btpcli/facade_accounts_subaccount_test.go

* This PR enables the option to provide an empty plan name when executing an app subscription. This scenario can occur if the subscribing account is in the same account as the one providing the app subscription
* Fixes #342 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
go test ./...
```
n/a

feat: subscription with empty plan name

---

internal/btpcli/client.go
internal/btpcli/client_test.go
internal/btpcli/clienttypes.go
internal/provider/provider.go
internal/provider/provider_test.go

This is a follow up for PR #406 adapting latest changes to the idtoken login endpoint in the btp CLI server.
The idtoken based login is now providing authentication information and is therefore compatible again with the btp_whoami data source.
Furthermore, the error handling on server side was improved which is resulting in more helpful error messages for the terraform user.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
go test ./...
```
```
...
```
* ...
The …

feat: improve id token login

---

.devcontainer/default/devcontainer.json
.devcontainer/withenvfile/devcontainer.json
.github/workflows/test.yml

* This PR pins the Terraform binaries (falling under BUSL/BSL license with the update to 1.6) to 1.5.7
* This is in response to the request of the SAP OSPO and their ongoing clarification with Hashicorp
* The change does not impact the provider but the dev container definition as well as the test matrix
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: version pinning
```
Create a new dev container
Terraform CLI version is 1.5.7
n/a

chore: pin Terraform CLI version to 1.5.x

---

docs/data-sources/subaccount_trust_configuration.md
docs/data-sources/subaccount_trust_configurations.md
docs/resources/subaccount_trust_configuration.md
internal/btpcli/facade_security_trust.go
internal/btpcli/facade_security_trust_test.go
internal/btpcli/types/xsuaa_trust/trust_configuration_response_object.go
internal/provider/datasource_subaccount_trust_configuration.go
internal/provider/datasource_subaccount_trust_configurations.go
internal/provider/fixtures/datasource_subaccount_trust_configuration.custom_idp_exists.yaml
internal/provider/fixtures/datasource_subaccount_trust_configuration.custom_idp_not_existing.yaml
internal/provider/fixtures/datasource_subaccount_trust_configuration.default.yaml
internal/provider/fixtures/datasource_subaccount_trust_configurations.subaccount_exists.yaml
internal/provider/fixtures/datasource_subaccount_trust_configurations.subaccount_not_existing.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.complete.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.minimal.yaml
internal/provider/resource_globalaccount_trust_configuration.go
internal/provider/resource_subaccount_trust_configuration.go
internal/provider/resource_subaccount_trust_configuration_test.go
internal/provider/type_subaccount_trust_configuration.go
internal/tfutils/tfutils.go

- add update operation to btp_subaccount_trust_configuration (covers the subaccount part of issue #372)
- add defaults to optional computed attributes which need to be updated when removed from the resource configuration
- make 'origin' computable (and no longer optional) since it cannot be set for subaccounts, resolves #392
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[X] Feature
```
```bash
go test ./...
```
```
...
```
* ...
The following organizational tasks must be completed before …

feat: support update of subaccount trust configurations

---

internal/provider/resource_directory.go

* This PR fixes a Sonar Cloud code smell concerning duplication of identical strings used in error messages.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Sonar Cloud Code Smell
```
```bash
go test ./...
```
n/a

fix: sonar cloud code smell - error message header

---

.devcontainer/default/devcontainer.json
.devcontainer/withenvfile/devcontainer.json

* Set TF CLI version in devcontainer back to latest
* closes #479
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: dev setup
```
```bash
go test ./...
```
n/a

chore: remove version pinning of TF CLI in devcontainer

---

internal/provider/fixtures/resource_directory.error_change_features.yaml
internal/provider/fixtures/resource_directory.full_config.yaml
internal/provider/fixtures/resource_directory.with_features.yaml
internal/provider/fixtures/resource_directory.yaml
internal/provider/fixtures/resource_subaccount.change_to_used_for_production.yaml
internal/provider/fixtures/resource_subaccount.full_config.yaml
internal/provider/fixtures/resource_subaccount.used_for_production.yaml
internal/provider/fixtures/resource_subaccount.yaml
internal/provider/resource_directory.go
internal/provider/resource_directory_test.go
internal/provider/resource_subaccount.go
internal/provider/resource_subaccount_test.go

* This PR removes the `computed`attribute from the labels of the resources `directory` and `subaccount`
* Due to this change the planmodifier can be removed as it has no impact which corresponds to the [documentation](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework@v1.4.1/resource/schema/mapplanmodifier#UseStateForUnknown). Consequently, two tests needed adjustements 
* Closes #467
```
[X] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a
The following …

fix: handling of labels on subaccount and directory

---

internal/btpcli/client.go
internal/btpcli/client_test.go
internal/btpcli/clienttypes.go
internal/btpcli/clienttypes_test.go

* Remove unused code for client logout
* closes #490 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

fix: remove unused code for logout

---

internal/provider/fixtures/resource_subaccount_trust_configuration.error_missing_identityprovider.yaml
internal/provider/resource_subaccount_trust_configuration.go
internal/provider/resource_subaccount_trust_configuration_test.go

* This PR enables the handling of the default trust configuration with origin `sap.default`. 
* In order to enable a consistent handling several changes needed to be made in the resource:
* The static validation of the field `identity_provider` was removed to allow the provisioning of an empty string ( sap.default IdP does not fill this field)
* The validation is postponed to runtime
* The `CREATE` always requires a non-empty  `identity_provider` field. The SAP default IdP cannot be created the API throws an error when the IdP would be created a second time
* The `UPDATE` requires the validation if the origin is not `sap.default`
* The `DELETE` needs a special handling as the sap.default IdP cannot be deleted (API error), hence, we just remove the resource from the state
* Closes #504 …

fix: handling of trust configuration for SAP default idp

---

internal/btpcli/facade_services_instance.go

* This PR reverts the removal of the workaround for the calls of the service manager due to flaws in the downstream API. The workaround will now be kept as it ensures the stability of the calls to this platform API 
* Closes #520 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
Partially reverts #498 

fix: nil pointer error creation of service instance

---

docs/index.md
internal/provider/provider.go
internal/provider/provider_test.go

* Renaming of potentially confusing parameter for x509 auth in provider configuration 
```
[X] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: improvement of usability
```
```bash
go test ./...
```
Potential internal refactoring can be done as a follow-up, but not a obligatory action

fix: renamed provider config parameter for consistency

---

internal/provider/fixtures/resource_subaccount_trust_configuration.complete.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.error_missing_identityprovider.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.import_error.yaml
internal/provider/fixtures/resource_subaccount_trust_configuration.minimal.yaml
internal/provider/resource_subaccount_trust_configuration.go
internal/provider/resource_subaccount_trust_configuration_test.go

The domain is no longer reset to null if omitted in btp CLI command for updating a subaccount trust configuration.
This PR fixes the corresponding resource by changing the domain to computed and reading from state is unknown.
* ...
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
...
```
* ...

fix: adapt to command changes from XSUAA-3964

---

internal/provider/datasource_globalaccount_roles_test.go
internal/provider/provider_test.go

Enables to configure different global accounts for test recordings. Defaults to terraformintcanary.
```
[ ] Yes
[  x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Other... Please describe: Test Extension
```
```bash
go test ./...
```
```
* Execute Tests in provider_test.go 
* Set environment variable BTP_GLOBALACCOUNT to different global account and re-run. 
```
Building block for #59 

test: Configurable Global Accounts For Tests

---

internal/provider/datasource_directory_labels_test.go
internal/provider/fixtures/datasource_directory_labels.yaml

* Removes IDs for landscape independent test recording.
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```

test: Removes IDs From Directory Labels Test

---

internal/provider/datasource_directory_user_test.go
internal/provider/datasource_subaccount_user_test.go
internal/provider/datasource_subaccount_users_test.go
internal/provider/fixtures/datasource_directory_user.custom_idp.yaml
internal/provider/fixtures/datasource_directory_user.default_idp.yaml
internal/provider/fixtures/datasource_directory_users.custom_idp.yaml
internal/provider/fixtures/datasource_directory_users.default_idp.yaml
internal/provider/fixtures/datasource_directory_users.non_existing_idp.yaml
internal/provider/fixtures/datasource_globalaccount.yaml
internal/provider/fixtures/datasource_subaccount_user.yaml
internal/provider/fixtures/datasource_subaccount_users.custom_idp.yaml
internal/provider/fixtures/datasource_subaccount_users.default_idp.yaml

```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
Note: The datasource subaccount user tests also tested datasource directory user functionality. I suspect this to be a copy and paste error. Corresponding tests have been changed to test the datasource subaccount user functionality.

chore: removes IDs From Datasource Directory User, Datasource Subaccount User, Datasource Subaccount Users Tests

---

.github/workflows/test.yml

* Adjustment of test workflow due to breaking change of upload Action
* The new version uploads the coverage report from the latest Terraform version only for later processing by Sonar Cloud
* This PR overrules PR #616
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[] Other... Please describe:
```
```bash
go test ./...
```
For details of breaking change see <https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes>

chore: changes in test workflow for coverage upload

---

integration/README.md
integration/main.tf
integration/variables.tf

Up to know the trust configuration in the integration GA setup script was hard coded. This change introduces the ability to flexibly configure the test IDP and set origin keys for other trusted IDPs. This change introduces also a variable for extending subdomains of subaccounts to be able to configure multiple GAs in the same landscape.
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Other... Please describe:
```
* Create a new Global Account according to integration/README.md
* Configure the Global Account using the provided Terraform files. 
* Successful creation of all defined resources.
* The …

ci: Adds flexible IDP configuration to GA setup TF scripts

---

DEVELOPER.md

* Wrong path to devcontainer config in documentation
* fixes #667 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Run the GH workflow to check for broken Links
* GH Workflow passes
Validated via <https://github.com/SAP/terraform-provider-btp/actions/runs/7607550684>

docs: wrong path to devcontainer configuration

---

.github/workflows/release.yml

* Temporary fix of release workflow to exclude sonar cloud check
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: temporary workaround for release workflow
```
Execute release workflow
* Only the goreleaser is executed
Follow-up issue is created: #671 

chore: remove test step for release

---

.github/workflows/prerelease-check.yml
.github/workflows/release.yml
.github/workflows/schema-regression-test.yml

* This PR re-activates the regression test for the release workflow as mandatory prerequisite
* The workflow for schema regression test is improved by also reacting on "hard" errors from the `terraform plan` step which might occur
* Added a workflow `prerelease-check.yml` that can be manually triggered in order to execute the checks before the release in an isolated way
* Closes #650 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: GitHub workflow setup
```
Execute the workflows
Workflows are executed in accordance to the constraints
n/a
The following organizational tasks must be …

chore: setup of pre-release checks

---

.github/dependabot.yml

* Add `devcontainer` ecosystem to dependabot
* Closes #683 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Dependabot setup
```
* Check scheduled dependabot run
See <https://github.blog/changelog/2024-01-24-dependabot-version-updates-support-devcontainers/> and <https://containers.dev/guide/dependabot>.

chore: update dependabot for devcontainers

---

.github/release.yml
regression-test/provider.tf

* Pin provider version for regression test to 1.0.0
* Add label `github_actions`
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Internal Setup
```
* Execute release precheck GH Action
* Provider version 1.0.0 is taken
n/a

chore: pin GA version for regression

---

docs/data-sources/subaccount.md
examples/data-sources/btp_subaccount/data-source.tf

* This PR adds an example for the datasource `subaccount` and the option to fetch data via subdomain and region
* Example was missed in PR #727 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Check the documentation
* Examples for different variants are available
Original issue: #272 

docs: add example for subaccount data source

---

internal/provider/type_subaccount_service_binding.go

* Response structure of CREATE and GET for Service Bindings differ. 
* This PR implements the safeguarding of NIL reference in this diff
* Closes #757 757
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
Seems to be an issue specifically with Cloud Logging, however due to API of service manager we must cover this diff on our side

fix: make binding state response more resillient

---

regression-test/provider.tf

- Revert provider version to 1.0
We should keep it to 1.0.0 as customers can start with 1.0.0 and then jump to any minor versions.
* Prep work for release v1.2.0
* regression-test should be pinned to 1.0.0 as customers can jump from this to any minor version
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: regression-test fix
```
n/a
* ...

chore: release-120 fix fix-regression-test version

---

internal/provider/resource_subaccount_service_instance.go

* This PR implements a solution to transport the human readable error message for service instance creation/update/deletion
* Due to the inconsistency between the Swagger document of the service manager and the API response we must handle the mapping in a manual setup in the service instance resource
* closes #764 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
Old NGPBUG that lead to a change in the model for `OperationResponseObject ` used for JSON deserialization is: …

fix: transfer human readable error message from service broker

---

main.go

* Workaround for tf-docs-plugin issue as described in <https://github.com/hashicorp/terraform-plugin-docs/issues/355>
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: version pinning
```
```bash
make generate
```
* Automated tests are executed successfully: header of docs contains links and bullet lists (see e.g. resource for directory
- See GitHub Action run for diff: <https://github.com/SAP/terraform-provider-btp/actions/runs/8698319409/job/23855116473>
- Follow-up issue is #774 

chore: set tf docs plugin version to 0.18.0

---

.github/workflows/release.yml

* Fix permission propagation to reusable workflows
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: GitHub Action Setup
```
* Execute GH Action for release
* GH Action gets executed without issues
n/a

chore: fix permission for reusable workflow

---

.devcontainer/default/devcontainer.json
.devcontainer/scripts/install-xdg.sh
.devcontainer/withenvfile/devcontainer.json

* Install `xdg-utils` as post create step in devcontainer setup
* This enables the usage of the SSO option from the devcontainer, namely opening the browser
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Devcontainer setup
```
* Rebuild the devcontainer
* `xdg tools` are installed e.g. by entering `xdg-open`
fixes #804 

chore: update devcontainer config to enable SSO option

---

internal/btpcli/facade_services_instance.go

This PR addresses the issue mentioned in #834. 
The BadRequest error was due to the service instances being read by their name after its creation. Thus the provider was unable to distinguish between two instances with the same name (although in different environments). 
A change was made to read the instances by their ID instead, which is a unique identifier which resolves the above mentioned issue.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
go test ./...
```
The following …

fix: allow creation of duplicate service instances in different environments

---

internal/provider/resource_subaccount_entitlement.go

This PR resolves issue #837 
The issue at hand highlights the lack of a relevant error message when attempting to destroy entitlements under specific conditions. One such scenario arises when trying to destroy an entitlement for which a service instance exists outside of Terraform's lifecycle.
To address this, an update has been made to the `Delete()` function of the `resourceSubaccountEntitlement`. This update allows the error message to be propagated from the `AssignedServicePlanSubaccountDto` response object, providing more informative feedback during the destruction process.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] Other... Please …
```

fix: Improved Error Handling for Entitlement Destruction

---

internal/provider/resource_subaccount_subscription.go

This PR provides a temporal workaround for #848 
The timeout for subaccount application subscriptions has been increased from 10 minutes to 60 minutes to accommodate scenarios where the subscription process may take longer.
Instead of making the timeout a configurable parameter in the resource, the values for the Create and Delete functions were adjusted to avoid a schema change..
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```bash
go test ./...
```
The following organizational tasks must be …

feat: increased timeout for resource subaccount subscription

---

internal/provider/provider.go

* Fix for the situation if username/password as well as ID Token is provided via ENV variables
* Closes #853
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
```
Provide username/password as well as the ID Token (random value) via ENV variables
Execute a terraform plan
```
* An error message is raised when the additional test step is executed
n/a

fix: check for multiple auth parameters

---

.github/workflows/test.yml

* Increase timeout limit for tests to safeguard against long running test recordings (like service instance)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: test setup
```
```bash
go test ./...
```
* Tests do not timeout
As we cannot automatically cleanup the test fixtures this increase of the timeout safeguards the test runs against timeouts esp. for relases

chore: timeout for test runs

---

.github/workflows/schema-regression-test.yml
regression-test/provider.tf

Tenant on the productive landscape seems to be broken, due to which the regression tests are failing. 
The idp has been removed as a temporary fix. 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
go test ./...
```

fix: removed idp from regression tests

---

internal/provider/datasource_subaccount.go

* Fix wrong setting of placeholders in error message for the datasource `subaccount`
* Closes #870
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
go test ./...
```
n/a

fix: empty placeholders in error message

---

internal/provider/resource_subaccount_entitlement.go
internal/provider/resource_subaccount_service_instance.go
internal/provider/resource_subaccount_subscription.go

* Add retry logic in case of rate limiting to the following resources:
* subaccount_entitlement
* subaccount_service_instance
* subaccount_subscription
* Increase waiting time for entitlement assignment/creation and deletion to avoid unnecessary retries when hitting a rate limit
* Closes #872
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
go test ./...
```
```
Execute assignment of entitlements in parallel to hit rate limit error
```
* Verify that rate limit error …

feat: add retry logic for rate limit for entitlement

---

docs/resources/directory_api_credential.md
docs/resources/globalaccount_api_credential.md
docs/resources/subaccount_api_credential.md
internal/provider/resource_directory_api_credential.go
internal/provider/resource_globalaccount_api_credential.go
internal/provider/resource_subaccount_api_credential.go

* Add link from help.sap.com for API credentials resource
* Closes #912
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
go test ./...
```
* Check markdown to contain same link as help.sap.com
Validated layout of markdown files at https://registry.terraform.io/tools/doc-preview

docs: fix wrong link for API credentials

---

internal/provider/resource_subaccount_entitlement.go
internal/provider/resource_subaccount_environment_instance.go
internal/tfutils/retry.go
internal/tfutils/retry_test.go

* Add retry logic for Gateway timeouts for environment instances
* Refactor/centralize existing retry logic for entitlements
* Closes #985
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
go test ./...
```
n/a

feat: add retry logic for Gateway timeout

---

.github/workflows/release.yml
.github/workflows/schema-regression-test-opentofu.yml
.github/workflows/schema-regression-test.yml
.github/workflows/test.yml

* Set caching to false in GH Actions to get rid of warning of `Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2`
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: GH Action setup
```
```bash
go test ./...
```
The fix for the open Tofu setup is available via PR #993

chore: go setup in GH Actions

---

internal/provider/resource_subaccount_subscription.go

- The resource `btp_subaccount_subscription` does not support update operations. This results in an error if Terraform would trigger a update in the execution phase
- Currently a require replace is only set for the parameters
- This could lead to issues for customers when trying to update e.g. the plan of the subscription, e. g. to first manually delete the subscription before applying the change in a newly created resource
- This PR adds the plan modifer `stringplanmodifier.RequiresReplace(),` to the schema attributes `subaccount`, `app_name` and `plan_name` to mitigate this
- Closes #1018
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
[ ] …
```

feat: add automatic replace to resource 'subscription'

---

docs/resources/subaccount_role.md
internal/provider/resource_directory_role.go
internal/provider/resource_globalaccount_role.go
internal/provider/resource_subaccount_entitlement.go
internal/provider/resource_subaccount_role.go

- Unify handling of drift detection when resource is manually removed from platform
- Adjustments in resources: `btp_*_role` and `btp_subaccount_entitlement`
- The handling is based on Terraform's best practises to deal with HTTP 404 statsu codes in READ operations: <https://developer.hashicorp.com/terraform/plugin/framework/resources/read#recommendations>
- The resource `btp_subacccount_entitlement` has a special handling as the reading does not directly return a 404, but semantically the situation can be identified
- Closes #1033 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
- Test the code via automated …

fix: drift detection for roles and subaccount entitlement

---

.github/workflows/test-opentofu.yml
.github/workflows/test.yml

- Update test matrix for Terraform and OpenTofu version wrt to their end of life
- Update Terraform test setup to use a dedicated GH Action to display the test result in a more visual way
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
For EOL information see:
- https://endoflife.date/terraform
- https://endoflife.date/opentofu

chore: test setup

---

docs/resources/globalaccount_resource_provider.md
examples/resources/btp_globalaccount_resource_provider/resource.tf

- Fix wrong example for resource `btp_globalaccount_resource_provider` to match schema
- Closes #1046
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
- Check the generated documentation that example matches schema
n/a

docs: fix wrong example for resource provider

---

docs/resources/directory_api_credential.md
docs/resources/globalaccount_api_credential.md
docs/resources/subaccount_api_credential.md
internal/provider/resource_directory_api_credential.go
internal/provider/resource_globalaccount_api_credential.go
internal/provider/resource_subaccount_api_credential.go

- Fix broken link for "Further Documentation" of resource `btp_subaccount_api_credential`
- closes #912
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```
Link that was used pointed to draft version of help.sap.com

fix: broken link to API credential resource

---

internal/provider/helper.go
internal/provider/provider.go
internal/provider/resource_directory.go
internal/provider/resource_directory_api_credential.go
internal/provider/resource_directory_entitlement.go
internal/provider/resource_directory_role.go
internal/provider/resource_directory_role_collection.go
internal/provider/resource_globalaccount_api_credential.go
internal/provider/resource_globalaccount_resource_provider.go
internal/provider/resource_globalaccount_role.go
internal/provider/resource_globalaccount_role_collection.go
internal/provider/resource_globalaccount_security_settings.go
internal/provider/resource_globalaccount_trust_configuration.go
internal/provider/resource_subaccount.go
internal/provider/resource_subaccount_api_credential.go
internal/provider/resource_subaccount_environment_instance.go
internal/provider/resource_subaccount_role.go
internal/provider/resource_subaccount_role_collection.go
internal/provider/resource_subaccount_security_settings.go
internal/provider/resource_subaccount_service_binding.go
internal/provider/resource_subaccount_service_broker.go
internal/provider/resource_subaccount_service_instance.go
internal/provider/resource_subaccount_subscription.go
internal/provider/resource_subaccount_trust_configuration.go

This PR closes #1060
Since unsubscribed subscriptions returned a ```200``` status code instead of a ```404```, the ```handleReadErrors()``` inside the ```internal/provider/helper.go``` file,  does not handle the drift detection for subscriptions deleted outside terraform.
Thus a check has been added against the ```state``` attribute of subscriptions in the same function. With this in place, drift for deleted subscriptions will now be handled properly.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```bash
make test
```
- Automated tests are …

fix: handling drift detection for subscriptions

---

docs/resources/subaccount.md
internal/provider/resource_subaccount.go
internal/provider/resource_subaccount_test.go
internal/provider/type_subaccount.go
templates/resources/subaccount.md.tmpl

- Relax validation of subdomain attribute:
- no more attribute validation vioa schema
- warning if subdomain is not following the proposed pattern
- closes #1105
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
The hard check would be a blocker for importing subaccounts that do not follow the proposed pattern.
Now a warning is raised during create: 

feat: relax constraint for subdomain naming convention

---

btp/provider/resource_subaccount_subscription.go
docs/resources/subaccount_subscription.md

- Fixes update error when importing a subscription with a timeout
- Added timeout for update to schema
- Regenerated the documentation
- closes #1132
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```
Due to the nature of the timeout blocks, the import of a resource with a timeout block will result in a two step operation:
- First the resource will be imported
- A in-place update of the resource will be triggered to add the timeout block to the state
The in-place update has no …

fix: handling of timeout block for import of subscriptions

---

btp/provider/fixtures/resource_subaccount_security_settings.complete.yaml
btp/provider/fixtures/resource_subaccount_security_settings.destroy.yaml
btp/provider/fixtures/resource_subaccount_security_settings.destroy_list.yaml
btp/provider/fixtures/resource_subaccount_security_settings_with_iframe_domains_list.complete.yaml
btp/provider/resource_subaccount_security_settings.go
btp/provider/resource_subaccount_security_settings_test.go
btp/provider/type_subaccount_security_settings.go
docs/resources/subaccount_security_settings.md

- Fixes the error when importing a security setting via the `-generate-config-out` parameter
- As a consequence of the fix the attribute `iframe_domains_list` must be used for the import after this fix
- The parameter `iframe_domains` is deprecated and will be removed in the next **major** release
- All existing security settings created via previous provider version are not impacted by this change
- closes #1135
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
The …

fix: import of security settings via configuration generation

---

btp/provider/datasource_whoami.go
internal/btpcli/client.go
internal/btpcli/client_test.go
internal/btpcli/clienttypes.go
internal/btpcli/session.go

- Align the login flows with the current version of the SAP BTP CLI wire protocoll namely:
- Only “issuer” and “mail” are in the response for any login flow. Mapping in response and setting to Session /v2LoggedInUser struct can be removed
- For the browser login the response mapping can be unified with the regular login flow
- For the Browser login the SessionId must be fetched from the response header
- In additon the `whoami` data source was adjusted to use the email field as ID. As of now the ID field was empty as the field is not transfered by the CLI server upon login
- closes #1139
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] …
```

chore: align login flows to wire protocoll

---

btp/provider/resource_subaccount.go
internal/validation/labelvalidator/labelvalidator.go
internal/validation/labelvalidator/labelvalidator_test.go

- Add a custom vlaidator for labels to the resource `btp_subaccount`
- See also: https://api.sap.com/api/APIAccountsService/path/createSubaccountLabels
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
In case of a production setup the missing validation leads to issues in the flow:
- A PR is opened with a subaccount configuration that contains invalid labels. A validation via `terraform validate` or a preliminary planning via `terraform plan` will not fail.
- The PR gets merged …

fix: validate labels for subaccount
